sensors:
  - name: "bosch pst-ft-2 (temperature)"
    x_values: [89.28, 112.7, 144.2, 186.6, 243.1, 322.5, 435.6, 595.4, 833.8, 1174, 1706, 2056, 2499, 3791, 5895, 9395, 15458, 26108, 45303]
    y_values: [130, 120, 110, 100, 90, 80, 70, 60, 50, 40, 30, 25, 20, 10, 0, -10, -20, -30, -40]
    can_id: 0xb003
    can_data_offset: 0
    can_data_width: 2
    column_index: 0
    row_index: 0
    offset: -3.000000
    id: 1

  - name: "delphi 25036751 (temperature)"
    x_values: [52.6, 59.4, 67.3, 76.4, 87, 99.4, 113.9, 131, 151.3, 175.3, 203.9, 238.1, 279, 329, 389, 462, 551, 660, 796, 965, 1177, 1443, 1778, 2205, 2752, 3457, 4373, 5572, 7153, 9256, 12073, 15873, 21044, 28146, 37994, 51791, 71332, 99326]
    y_values: [145, 140, 135, 130, 125, 120, 115, 110, 105, 100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0, -5, -10, -15, -20, -25, -30, -35, -40]
    can_id: 0xb003
    can_data_offset: 2
    can_data_width: 2
    column_index: 1
    row_index: 0
    id: 2

  - name: "aem 30-2011 (temperature)"
    x_values: [180, 500, 1500, 3700, 9800, 29000, 100000]
    y_values: [100, 70, 40, 20, 0, -20, -40]
    can_id: 0xb003
    can_data_offset: 4
    can_data_width: 2
    column_index: 2
    row_index: 0
    offset: -4.000000
    id: 3

  - name: "bosch pst-ft (pressure)"
    x_values: [0, 500, 4500]
    y_values: [-1.25, 0, 10]
    can_id: 0xb000
    can_data_offset: 0
    can_data_width: 2
    column_index: 0
    row_index: 1
    id: 4

  - name: "bosch pst-ft (pressure)"
    x_values: [0, 500, 4500]
    y_values: [-1.25, 0, 10]
    can_id: 0xb000
    can_data_offset: 2
    can_data_width: 2
    column_index: 1
    row_index: 1
    id: 5

  - name: "TPMS multiplexor channel"
    can_id: 0x77e
    can_data_offset: 0
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 6

  - name: "TMPS pressure channel"
    can_id: 0x77e
    can_data_offset: 1
    can_data_width: 2
    column_index: 2
    row_index: 1
    scale: 0.001000
    id: 6

  - name: "TMPS temperature channel"
    can_id: 0x77e
    can_data_offset: 3
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 6

  - name: "TMPS voltage channel"
    can_id: 0x77e
    can_data_offset: 4
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 6

  - name: "ECUMaster GPS Lattiude"
    can_id: 0x400
    can_data_offset: 0
    can_data_width: 4
    column_index: 2
    row_index: 1
    scale: 0.000000
    id: 7

  - name: "ECUMaster GPS Longitude"
    can_id: 0x400
    can_data_offset: 4
    can_data_width: 4
    column_index: 2
    row_index: 1
    scale: 0.000000
    id: 7

  - name: "ECUMaster GPS Speed"
    can_id: 0x401
    can_data_offset: 0
    can_data_width: 2
    column_index: 2
    row_index: 1
    scale: 0.036000
    id: 7

  - name: "ECUMaster GPS Altitude"
    can_id: 0x401
    can_data_offset: 2
    can_data_width: 2
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMasters Sat Count"
    can_id: 0x401
    can_data_offset: 5
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMasters GPS Status"
    can_id: 0x401
    can_data_offset: 7
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMaster GPS Heading Motion"
    can_id: 0x402
    can_data_offset: 0
    can_data_width: 2
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMaster GPS Vehicle Motion"
    can_id: 0x402
    can_data_offset: 2
    can_data_width: 2
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMaster GPS X Acceleration"
    can_id: 0x403
    can_data_offset: 2
    can_data_width: 2
    column_index: 2
    row_index: 1
    scale: 0.010000
    id: 7

  - name: "ECUMaster GPS Y Acceleration"
    can_id: 0x403
    can_data_offset: 4
    can_data_width: 2
    column_index: 2
    row_index: 1
    scale: 0.010000
    id: 7

  - name: "ECUMaster GPS Y Acceleration"
    can_id: 0x403
    can_data_offset: 6
    can_data_width: 2
    column_index: 2
    row_index: 1
    scale: 0.010000
    id: 7

  - name: "ECUMasters UTC Year"
    can_id: 0x404
    can_data_offset: 0
    can_data_width: 1
    column_index: 2
    row_index: 1
    offset: 2000.000000
    id: 7

  - name: "ECUMasters UTC Month"
    can_id: 0x404
    can_data_offset: 1
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMasters UTC Day"
    can_id: 0x404
    can_data_offset: 2
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMasters UTC Hour"
    can_id: 0x404
    can_data_offset: 3
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMasters UTC Minute"
    can_id: 0x404
    can_data_offset: 4
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 7

  - name: "ECUMasters UTC Second"
    can_id: 0x404
    can_data_offset: 5
    can_data_width: 1
    column_index: 2
    row_index: 1
    id: 7


panels:
  - type: radial_temperature
    column_index: 0
    row_index: 0
    layer_index: 0
    border: 1
    id: 1
    label: "Water"
    min_value: 0.0
    max_value: 120.0
    low_warn : -27.0
    high_warn: 105.0
    output_format: "%.0f"
    units: "°F"

  - type: radial_temperature
    column_index: 0
    row_index: 0
    layer_index: 1
    border: 1
    id: 1
    label: "Water"
    min_value: 0.0
    max_value: 120.0
    low_warn : -27.0
    high_warn: 105.0
    output_format: "%.0f"
    units: "°C"

  - type: radial_temperature
    column_index: 1
    row_index: 0
    layer_index: 1
    border: 1
    id: 2
    label: "Intake"
    min_value: -40.0
    max_value: 65.0
    low_warn : 0.0
    high_warn: 70.0
    output_format: "%.0f"
    units: "°C"

  - type: radial_temperature
    column_index: 1
    row_index: 0
    layer_index: 0
    border: 1
    id: 2
    label: "Intake"
    min_value: 0.0
    max_value: 130.0
    low_warn : -10.0
    high_warn: 110.0
    output_format: "%.0f"
    units: "°F"

  - type: linear_temperature
    column_index: 2
    row_index: 0
    layer_index: 0
    border: 1
    id: 3
    label: "Oil"
    min_value: -1.000
    max_value: 220.000
    low_warn : 60.0
    high_warn: 180.0
    output_format: "%.0f"
    units: "°F"

  - type: linear_temperature
    column_index: 2
    row_index: 0
    layer_index: 1
    border: 1
    id: 3
    label: "Oil"
    min_value: -1.000
    max_value: 105.000
    low_warn : 16.0
    high_warn: 82.0
    output_format: "%.0f"
    units: "°C"

  - type: radial_temperature
    column_index: 2
    row_index: 0
    layer_index: 2
    border: 1
    id: 3
    label: "Oil"
    min_value: -1.0
    max_value: 220.0
    low_warn : 60.0
    high_warn: 180.0
    output_format: "%.0f"
    units: "°F"

  - type: radial_pressure
    column_index: 0
    row_index: 1
    layer_index: 0
    border: 1
    id: 4
    label: "Oil"
    min_value: 0.0
    max_value: 8.0
    low_warn : 3.0
    high_warn: 5.5
    output_format: "%.0f"
    units: "bar"

  - type: radial_pressure
    column_index: 0
    row_index: 1
    layer_index: 1
    border: 1
    id: 4
    label: "Oil"
    min_value: 0.0
    max_value: 250.0
    low_warn : 40.0
    high_warn: 180.0
    output_format: "%.0f"
    units: "psi"

  - type: radial_pressure
    column_index: 1
    row_index: 1
    layer_index: 0
    border: 1
    id: 5
    label: "MAP"
    min_value: 1.0
    max_value: 4.0
    low_warn : 1.5
    high_warn: 3.5
    output_format: "%.0f"
    units: "bar"

  - type: radial_pressure
    column_index: 1
    row_index: 1
    layer_index: 1
    border: 1
    id: 5
    label: "MAP"
    min_value: -101.0
    max_value: 100.0
    low_warn : -1000.0
    high_warn: 1000.0
    output_format: "%.0f"
    units: "kPa"

  - type: radial_pressure
    column_index: 1
    row_index: 1
    layer_index: 2
    border: 1
    id: 5
    label: "MAP"
    min_value: 1.0
    max_value: 4.0
    low_warn : 1.5
    high_warn: 3.5
    output_format: "%.0f"
    units: "bar"

  - type: tpms
    column_index: 2
    row_index: 1
    layer_index: 0
    border: 1
    timeout: 1500
    id: 6

  - type: tpms
    column_index: 2
    row_index: 1
    layer_index: 1
    border: 1
    timeout: 1500
    id: 6

  - type: gps
    column_index: 2
    row_index: 1
    layer_index: 2
    border: 1
    timeout: 1500
    id: 7

